[package]
name = "ovault"
version = "0.1.0"
edition = "2021"
build = "./build.rs"

[lib]
name = "ovault"

[features]
default = []
python = ["pyo3", "syn", "quote"]

[dependencies]
pyo3 = { version = "0.23.4", optional = true }

[build-dependencies]
syn =  { version = "2.0.96", optional = true }
quote = { version = "1.0.38", optional = true }
